"""empty message

Revision ID: 82f7ca9cc56f
Revises: 011be0cae1bc
Create Date: 2020-05-24 22:07:21.652235

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '82f7ca9cc56f'
down_revision = '011be0cae1bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('document', sa.String(length=30), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('zip_code', sa.String(length=14), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('register_by', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document')
    )
    op.create_table('supplier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('document', sa.String(length=30), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('zip_code', sa.String(length=14), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('register_by', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('permission', sa.Enum('admin', 'operator'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('supply',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nota_fiscal', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=255), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('purchase_price', sa.DECIMAL(precision=14, scale=4), nullable=False),
    sa.Column('qtd', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('register_by', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id', 'nota_fiscal')
    )
    op.create_table('terminal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nota_fiscal', sa.String(length=50), nullable=False),
    sa.Column('brand', sa.String(length=255), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('terminal_type_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('terminal_state_id', sa.Integer(), nullable=False),
    sa.Column('purchase_price', sa.DECIMAL(precision=14, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('register_by', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.ForeignKeyConstraint(['terminal_state_id'], ['terminal_state.id'], ),
    sa.ForeignKeyConstraint(['terminal_type_id'], ['terminal_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supply_movement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supply_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('qtd', sa.Integer(), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=14, scale=4), nullable=False),
    sa.Column('register_by', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['supply_id'], ['supply.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('terminal_movement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('terminal_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=14, scale=4), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('movement_type', sa.Enum('venda', 'aluguel', 'manutenção'), nullable=True),
    sa.Column('register_by', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['terminal_id'], ['terminal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('email', table_name='users')
    op.drop_index('username', table_name='users')
    op.drop_table('users')
    op.drop_table('customers')
    op.drop_table('suppliers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('document', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('address', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('number', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('city', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('state', mysql.VARCHAR(length=2), nullable=False),
    sa.Column('zip_code', mysql.VARCHAR(length=14), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('register_by', mysql.VARCHAR(length=100), nullable=False),
    sa.CheckConstraint('(`status` in (0,1))', name='suppliers_chk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('customers',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('source_id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('source', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('document', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('address', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('number', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('city', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('state', mysql.VARCHAR(length=2), nullable=False),
    sa.Column('zip_code', mysql.VARCHAR(length=14), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('register_by', mysql.VARCHAR(length=100), nullable=False),
    sa.CheckConstraint('(`status` in (0,1))', name='customers_chk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('permission', mysql.ENUM('admin', 'operator'), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.CheckConstraint('(`status` in (0,1))', name='users_chk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('username', 'users', ['username'], unique=True)
    op.create_index('email', 'users', ['email'], unique=True)
    op.drop_table('terminal_movement')
    op.drop_table('supply_movement')
    op.drop_table('terminal')
    op.drop_table('supply')
    op.drop_table('user')
    op.drop_table('supplier')
    op.drop_table('customer')
    # ### end Alembic commands ###
