"""empty message

Revision ID: bafac89eea58
Revises: 44dd07b8bb51
Create Date: 2020-05-23 23:31:27.780505

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bafac89eea58'
down_revision = '44dd07b8bb51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('users', 'update_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('update_at', mysql.DATETIME(), nullable=True))
    op.drop_column('users', 'updated_at')
    # ### end Alembic commands ###
